### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by BlueGunk** [opparco/io_anim_hkx#4]
I dropped io_anim_hkx into Addons as instructed (I had to amend the file name by removing -master) and tried to import an HKX file. I got a string of errors and a "File not Found". Screen print attached.
![Blender HKX issues](https://user-images.githubusercontent.com/40629886/69899618-e94ac100-1360-11ea-9723-09d2c7e9f467.jpg)

I have tried a number of things with no luck.  I also do not know how or where to install HKDump (sorry!)

Please can you help? Thank you!

**Comment by UsingSession** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/30206863/103864601-91d26500-50cb-11eb-941e-bd5effdd33df.png)
Hello. You need load another file from release. Namely the **[file io_anim_hkx-001.zip](https://github.com/opparco/io_anim_hkx/releases/download/v0.0.1/io_anim_hkx-001.zip)**

**Comment by BlueGunk** [comment]
Thank you!
